# Site settings
title: Robot Tech Club
SEOTitle: My Blog | Longsen Gao
header-img: img/bkkhd.jpg
email: jackshine123@yahoo.com
description: "Longsen Gao"
keyword: "My Blog"
url: "http://gaolongsen.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/gaolongsen/gaolongsen.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Longsen(Shine) Gao"
sidebar-avatar: /img/self.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     暂无
#zhihu_username:     beng-fa-de-hai-yang
github_username:    gaolongsen
facebook_username:  profile.php?id=100025827457078
#jianshu_username:   暂无
#twitter_username:   暂无




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
#redcarpet:
#    extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Disqus（https://disqus.com/）
# disqus_username: Sherry_Gao123

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 02416484b7b4c8153de5  #生成的clientID
  clientSecret: 189b299d62951474954eb54822ae610d7317f28b    #生成的clientSecret
  repo: Comments   #仓库名称
  owner: gaolongsen     #github用户名
  admin: gaolongsen
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 
# Google Analytics
ga_track_id: G-RHY0B03W4V           # Format: UA-xxxxxx-xx
ga_domain: http://robothub.tech/    # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Mathwork",
        href: "https://www.mathworks.com/products/matlab.html"
    },
    {
        title: "ROS",
        href: "https://www.ros.org/"
    
    },
        {
        title: "Ubuntu",
        href: "https://ubuntu.com/"
    
    },
    {
        title: "Google Barin Team",
        href: "https://research.google/teams/brain/"
    },
    {
        title: "OpenAI",
        href: "https://openai.com/"
    },
    {
        title: "University of Michigan,Ann Arbor",
        href: "https://umich.edu/"
    },
    {
        title: "Carnegie Mellon University",
        href: "https://www.cmu.edu/"
    }    
]

